using Microsoft.EntityFrameworkCore;
using SafeSchool.Api.Features.AttendanceAccess;
using SafeSchool.Api.Features.AttendanceAccess.Anomalies;
using SafeSchool.Api.Features.AttendanceAccess.Attendance;
using SafeSchool.Api.Features.AttendanceAccess.Audit;
using SafeSchool.Api.Features.AttendanceAccess.Common;
using SafeSchool.Api.Features.AttendanceAccess.Common.Idempotency;
using SafeSchool.Api.Features.AttendanceAccess.Gates;
using SafeSchool.Api.Features.AttendanceAccess.Notifications;
using SafeSchool.Api.Features.AttendanceAccess.Reviews;
using SafeSchool.Api.Features.AttendanceAccess.Scans;
using SafeSchool.Api.Features.Communications;
using SafeSchool.Api.Features.Complaints;
using SafeSchool.Api.Features.IdentityAccess;
using SafeSchool.Api.Features.IdentityAccess.AccessControl;
using SafeSchool.Api.Features.IdentityAccess.Audit;
using SafeSchool.Api.Features.IdentityAccess.Credentials;
using SafeSchool.Api.Features.IdentityAccess.Guardians;
using SafeSchool.Api.Features.IdentityAccess.StudentProfiles;
using SafeSchool.Api.Features.Learning;
using SafeSchool.Api.Features.Learning.Audit;
using SafeSchool.Api.Features.Learning.Common.Idempotency;
using LearningDomain = SafeSchool.Api.Features.Learning.Domain;
using SafeSchool.Api.Features.Mobile;
using SafeSchool.Api.Features.Transport;
using SafeSchool.Api.Features.Transport.Anomalies;
using SafeSchool.Api.Features.Transport.Assignments;
using SafeSchool.Api.Features.Transport.Audit;
using SafeSchool.Api.Features.Transport.Common.Idempotency;
using SafeSchool.Api.Features.Transport.Eta;
using SafeSchool.Api.Features.Transport.Notifications;
using SafeSchool.Api.Features.Transport.Routes;
using SafeSchool.Api.Features.Transport.Rules;
using SafeSchool.Api.Features.Transport.Scans;
using SafeSchool.Api.Features.Transport.Tracking;
using SafeSchool.Api.Features.Transport.Trips;
using SafeSchool.Api.Features.Transport.Reviews;
using SafeSchool.Api.Features.Wallet;
using SafeSchool.Api.Features.Wallet.Anomalies;
using SafeSchool.Api.Features.Wallet.Audit;
using SafeSchool.Api.Features.Wallet.Canteen;
using SafeSchool.Api.Features.Wallet.Common.Idempotency;
using SafeSchool.Api.Features.Wallet.Corrections;
using SafeSchool.Api.Features.Wallet.Ledger;
using SafeSchool.Api.Features.Wallet.Limits;
using SafeSchool.Api.Features.Wallet.Payments;
using SafeSchool.Api.Features.Wallet.Pos;
using SafeSchool.Api.Features.Wallet.Reconciliation;
using SafeSchool.Api.Features.Wallet.Reviews;
using SafeSchool.Api.Features.Wallet.Rules;
using SafeSchool.Api.Features.Wallet.Sync;
using SafeSchool.Api.Features.Wallet.TopUps;
using SafeSchool.Api.Features.Wallet.Wallets;

namespace SafeSchool.Api.Infrastructure.Persistence;

public sealed class SafeSchoolDbContext(DbContextOptions<SafeSchoolDbContext> options) : DbContext(options)
{
    public DbSet<StudentProfile> StudentProfiles => Set<StudentProfile>();
    public DbSet<GuardianRecord> GuardianRecords => Set<GuardianRecord>();
    public DbSet<GuardianLink> GuardianLinks => Set<GuardianLink>();
    public DbSet<IdentityCredential> IdentityCredentials => Set<IdentityCredential>();
    public DbSet<NfcCardCredential> NfcCardCredentials => Set<NfcCardCredential>();
    public DbSet<QrFallbackCredential> QrFallbackCredentials => Set<QrFallbackCredential>();
    public DbSet<CredentialStatusSnapshot> CredentialStatusSnapshots => Set<CredentialStatusSnapshot>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<ActorRoleAssignment> ActorRoleAssignments => Set<ActorRoleAssignment>();
    public DbSet<AccessDecision> AccessDecisions => Set<AccessDecision>();
    public DbSet<AuditEvent> AuditEvents => Set<AuditEvent>();
    public DbSet<Gate> Gates => Set<Gate>();
    public DbSet<ScanPoint> ScanPoints => Set<ScanPoint>();
    public DbSet<GateScanEvent> GateScanEvents => Set<GateScanEvent>();
    public DbSet<OfflineSyncBatch> OfflineSyncBatches => Set<OfflineSyncBatch>();
    public DbSet<CampusAccessDecision> CampusAccessDecisions => Set<CampusAccessDecision>();
    public DbSet<AttendanceAccessRuleSettings> AttendanceAccessRuleSettings => Set<AttendanceAccessRuleSettings>();
    public DbSet<AttendanceAccessAuditEvent> AttendanceAccessAuditEvents => Set<AttendanceAccessAuditEvent>();
    public DbSet<AttendanceAccessIdempotencyRecord> AttendanceAccessIdempotencyRecords => Set<AttendanceAccessIdempotencyRecord>();
    public DbSet<AttendanceSession> AttendanceSessions => Set<AttendanceSession>();
    public DbSet<AttendanceRecord> AttendanceRecords => Set<AttendanceRecord>();
    public DbSet<EntryExitNotificationRecord> EntryExitNotificationRecords => Set<EntryExitNotificationRecord>();
    public DbSet<AttendanceAnomaly> AttendanceAnomalies => Set<AttendanceAnomaly>();
    public DbSet<ManualReview> ManualReviews => Set<ManualReview>();
    public DbSet<TransportRoute> TransportRoutes => Set<TransportRoute>();
    public DbSet<TransportStop> TransportStops => Set<TransportStop>();
    public DbSet<RouteStopSequence> RouteStopSequences => Set<RouteStopSequence>();
    public DbSet<TransportVehicle> TransportVehicles => Set<TransportVehicle>();
    public DbSet<StudentTransportAssignment> StudentTransportAssignments => Set<StudentTransportAssignment>();
    public DbSet<TransportTrip> TransportTrips => Set<TransportTrip>();
    public DbSet<OfflineTransportScanSyncBatch> OfflineTransportScanSyncBatches => Set<OfflineTransportScanSyncBatch>();
    public DbSet<BoardingDropScanEvent> BoardingDropScanEvents => Set<BoardingDropScanEvent>();
    public DbSet<TransportLocationUpdate> TransportLocationUpdates => Set<TransportLocationUpdate>();
    public DbSet<EtaRecord> EtaRecords => Set<EtaRecord>();
    public DbSet<TransportNotificationRecord> TransportNotificationRecords => Set<TransportNotificationRecord>();
    public DbSet<TransportAnomaly> TransportAnomalies => Set<TransportAnomaly>();
    public DbSet<ManualTransportReview> ManualTransportReviews => Set<ManualTransportReview>();
    public DbSet<TransportRuleSetting> TransportRuleSettings => Set<TransportRuleSetting>();
    public DbSet<TransportAuditEvent> TransportAuditEvents => Set<TransportAuditEvent>();
    public DbSet<TransportIdempotencyRecord> TransportIdempotencyRecords => Set<TransportIdempotencyRecord>();
    public DbSet<StudentWallet> StudentWallets => Set<StudentWallet>();
    public DbSet<WalletLedgerEntry> WalletLedgerEntries => Set<WalletLedgerEntry>();
    public DbSet<WalletTopUp> WalletTopUps => Set<WalletTopUp>();
    public DbSet<PaymentConfirmation> PaymentConfirmations => Set<PaymentConfirmation>();
    public DbSet<CanteenMerchant> CanteenMerchants => Set<CanteenMerchant>();
    public DbSet<CanteenItemCategory> CanteenItemCategories => Set<CanteenItemCategory>();
    public DbSet<PurchaseEligibilityRule> PurchaseEligibilityRules => Set<PurchaseEligibilityRule>();
    public DbSet<POSTerminal> PosTerminals => Set<POSTerminal>();
    public DbSet<OfflinePosSyncBatch> OfflinePosSyncBatches => Set<OfflinePosSyncBatch>();
    public DbSet<CanteenPurchaseTransaction> CanteenPurchaseTransactions => Set<CanteenPurchaseTransaction>();
    public DbSet<SpendingLimit> SpendingLimits => Set<SpendingLimit>();
    public DbSet<RefundOrReversal> RefundOrReversals => Set<RefundOrReversal>();
    public DbSet<ManualWalletReview> ManualWalletReviews => Set<ManualWalletReview>();
    public DbSet<WalletAnomaly> WalletAnomalies => Set<WalletAnomaly>();
    public DbSet<SettlementReference> SettlementReferences => Set<SettlementReference>();
    public DbSet<WalletReconciliationRun> WalletReconciliationRuns => Set<WalletReconciliationRun>();
    public DbSet<WalletReconciliationMismatch> WalletReconciliationMismatches => Set<WalletReconciliationMismatch>();
    public DbSet<WalletReviewSummary> WalletReviewSummaries => Set<WalletReviewSummary>();
    public DbSet<WalletRuleSetting> WalletRuleSettings => Set<WalletRuleSetting>();
    public DbSet<WalletAuditEvent> WalletAuditEvents => Set<WalletAuditEvent>();
    public DbSet<WalletIdempotencyRecord> WalletIdempotencyRecords => Set<WalletIdempotencyRecord>();
    public DbSet<LearningDomain.Course> LearningCourses => Set<LearningDomain.Course>();
    public DbSet<LearningDomain.LearningGroup> LearningGroups => Set<LearningDomain.LearningGroup>();
    public DbSet<LearningDomain.LearningGroupMembership> LearningGroupMemberships => Set<LearningDomain.LearningGroupMembership>();
    public DbSet<LearningDomain.StaffLearningAssignment> StaffLearningAssignments => Set<LearningDomain.StaffLearningAssignment>();
    public DbSet<LearningDomain.LearningContentItem> LearningContentItems => Set<LearningDomain.LearningContentItem>();
    public DbSet<LearningDomain.LearningProgressEvent> LearningProgressEvents => Set<LearningDomain.LearningProgressEvent>();
    public DbSet<LearningDomain.Assignment> LearningAssignments => Set<LearningDomain.Assignment>();
    public DbSet<LearningDomain.AssignmentSubmission> LearningAssignmentSubmissions => Set<LearningDomain.AssignmentSubmission>();
    public DbSet<LearningDomain.Quiz> LearningQuizzes => Set<LearningDomain.Quiz>();
    public DbSet<LearningDomain.QuizQuestion> LearningQuizQuestions => Set<LearningDomain.QuizQuestion>();
    public DbSet<LearningDomain.QuizAttempt> LearningQuizAttempts => Set<LearningDomain.QuizAttempt>();
    public DbSet<LearningDomain.QuizResponse> LearningQuizResponses => Set<LearningDomain.QuizResponse>();
    public DbSet<LearningDomain.StarRuleSetting> LearningStarRuleSettings => Set<LearningDomain.StarRuleSetting>();
    public DbSet<LearningDomain.StarLedgerEntry> LearningStarLedgerEntries => Set<LearningDomain.StarLedgerEntry>();
    public DbSet<LearningDomain.StarBalanceSnapshot> LearningStarBalanceSnapshots => Set<LearningDomain.StarBalanceSnapshot>();
    public DbSet<LearningDomain.RewardCatalogItem> LearningRewardCatalogItems => Set<LearningDomain.RewardCatalogItem>();
    public DbSet<LearningDomain.RewardRedemption> LearningRewardRedemptions => Set<LearningDomain.RewardRedemption>();
    public DbSet<LearningDomain.BehaviorCategory> LearningBehaviorCategories => Set<LearningDomain.BehaviorCategory>();
    public DbSet<LearningDomain.BehaviorEvent> LearningBehaviorEvents => Set<LearningDomain.BehaviorEvent>();
    public DbSet<LearningDomain.LearningException> LearningExceptions => Set<LearningDomain.LearningException>();
    public DbSet<LearningDomain.ManualLearningReview> ManualLearningReviews => Set<LearningDomain.ManualLearningReview>();
    public DbSet<LearningDomain.LearningRuleSetting> LearningRuleSettings => Set<LearningDomain.LearningRuleSetting>();
    public DbSet<LearningDomain.LearningReviewSummary> LearningReviewSummaries => Set<LearningDomain.LearningReviewSummary>();
    public DbSet<LearningDomain.SchoolAccountFeatureSetting> LearningFeatureSettings => Set<LearningDomain.SchoolAccountFeatureSetting>();
    public DbSet<LearningAuditEvent> LearningAuditEvents => Set<LearningAuditEvent>();
    public DbSet<LearningStatusEvent> LearningStatusEvents => Set<LearningStatusEvent>();
    public DbSet<LearningIdempotencyRecord> LearningIdempotencyRecords => Set<LearningIdempotencyRecord>();
    public DbSet<MobileUserProfile> MobileUserProfiles => Set<MobileUserProfile>();
    public DbSet<RoleWorkspace> MobileRoleWorkspaces => Set<RoleWorkspace>();
    public DbSet<RoleWorkspaceAction> MobileRoleWorkspaceActions => Set<RoleWorkspaceAction>();
    public DbSet<MobilePermissionGrant> MobilePermissionGrants => Set<MobilePermissionGrant>();
    public DbSet<TenantMobileFeatureAvailability> TenantMobileFeatureAvailabilities => Set<TenantMobileFeatureAvailability>();
    public DbSet<MobileLanguagePreference> MobileLanguagePreferences => Set<MobileLanguagePreference>();
    public DbSet<DeviceSession> MobileDeviceSessions => Set<DeviceSession>();
    public DbSet<ApkRelease> MobileApkReleases => Set<ApkRelease>();
    public DbSet<ReleaseAudience> MobileReleaseAudiences => Set<ReleaseAudience>();
    public DbSet<InstallOrUpgradeEvent> MobileInstallOrUpgradeEvents => Set<InstallOrUpgradeEvent>();
    public DbSet<OfflineActionQueue> MobileOfflineActionQueues => Set<OfflineActionQueue>();
    public DbSet<MobileAuditEvent> MobileAuditEvents => Set<MobileAuditEvent>();
    public DbSet<OperationalComplaintRecord> OperationalComplaints => Set<OperationalComplaintRecord>();
    public DbSet<OperationalComplaintEvent> OperationalComplaintEvents => Set<OperationalComplaintEvent>();
    public DbSet<OperationalComplaintIdempotencyRecord> OperationalComplaintIdempotencyRecords => Set<OperationalComplaintIdempotencyRecord>();
    public DbSet<OperationalCommunicationRecord> OperationalCommunications => Set<OperationalCommunicationRecord>();
    public DbSet<OperationalCommunicationEvent> OperationalCommunicationEvents => Set<OperationalCommunicationEvent>();
    public DbSet<OperationalCommunicationIdempotencyRecord> OperationalCommunicationIdempotencyRecords => Set<OperationalCommunicationIdempotencyRecord>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyIdentityAccessModel();
        modelBuilder.ApplyAttendanceAccessModel();
        modelBuilder.ApplyTransportModel();
        modelBuilder.ApplyWalletModel();
        modelBuilder.ApplyLearningModel();
        modelBuilder.ApplyMobileModel();
        modelBuilder.ApplyComplaintsOperationalModel();
        modelBuilder.ApplyCommunicationsOperationalModel();
    }
}
