import type { CSSProperties } from "react";
import { complaintsDemoData } from "../api/complaintsApi";

const styles: Record<string, CSSProperties> = { page: { minHeight: "100vh", background: "#f3f5f7", color: "#111827", padding: 32 }, header: { display: "flex", justifyContent: "space-between", gap: 24, alignItems: "start", marginBottom: 24 }, eyebrow: { fontSize: 13, fontWeight: 800, color: "#5b6472", textTransform: "uppercase" }, title: { fontSize: 40, margin: "6px 0" }, subtitle: { color: "#4b5563", maxWidth: 900, lineHeight: 1.5, fontSize: 18 }, badge: { border: "1px solid #bfdbfe", background: "#dbeafe", color: "#1d4ed8", padding: "10px 14px", borderRadius: 6, fontWeight: 800 }, nav: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 22 }, link: { border: "1px solid #cbd5e1", background: "#fff", borderRadius: 6, padding: "9px 12px", color: "#1f2937", textDecoration: "none", fontWeight: 800 }, grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14, marginBottom: 22 }, panel: { background: "#fff", border: "1px solid #d5dde6", borderRadius: 8, padding: 20, boxShadow: "0 1px 2px rgba(15,23,42,.06)" }, row: { padding: "10px 0", borderBottom: "1px solid #e5e7eb", color: "#4b5563" } };

export function ComplaintsDemo({ view = "overview", audience = "school" }: { view?: string; audience?: string }) {
  const metrics = complaintsDemoData.metrics;
  return <main style={styles.page}><header style={styles.header}><div><div style={styles.eyebrow}>SafeSchool Phase 8</div><h1 style={styles.title}>Complaints & Escalations</h1><p style={styles.subtitle}>Structured complaint intake, categorization, assignments, escalation, resolution, feedback, history, review, and audit evidence.</p></div><div style={styles.badge}>Demo data</div></header><nav style={styles.nav}><a style={styles.link} href="/complaints">Overview</a><a style={styles.link} href="/complaints/new">New</a><a style={styles.link} href="/complaints/history">History</a><a style={styles.link} href="/complaints/configuration">Configuration</a><a style={styles.link} href="/guardian/complaints">Guardian</a><a style={styles.link} href="/student/complaints">Student</a></nav><section style={styles.grid}>{metrics.map((metric) => <article key={metric.label} style={styles.panel}><strong style={{ fontSize: 32 }}>{metric.value}</strong><div>{metric.label}</div></article>)}</section><section style={styles.panel}><h2>{view} - {audience}</h2>{complaintsDemoData.rows.map((row) => <div key={row} style={styles.row}>{row}</div>)}<p style={{ color: "#64748b" }}>Tenant-scoped, permission-checked, audited, and side-effect bounded.</p></section></main>;
}
