import type { CSSProperties } from "react";
const documentsDemoData = { metrics: [{ label: "Documents", value: "128" }, { label: "Certificates", value: "34" }, { label: "Legal holds", value: "3" }], rows: ["Document uploaded and classified", "Certificate issued and verified", "Search result opened after access revalidation"] };

const styles: Record<string, CSSProperties> = { page: { minHeight: "100vh", background: "#f3f5f7", color: "#111827", padding: 32 }, header: { display: "flex", justifyContent: "space-between", gap: 24, alignItems: "start", marginBottom: 24 }, eyebrow: { fontSize: 13, fontWeight: 800, color: "#5b6472", textTransform: "uppercase" }, title: { fontSize: 40, margin: "6px 0" }, subtitle: { color: "#4b5563", maxWidth: 900, lineHeight: 1.5, fontSize: 18 }, badge: { border: "1px solid #bfdbfe", background: "#dbeafe", color: "#1d4ed8", padding: "10px 14px", borderRadius: 6, fontWeight: 800 }, nav: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 22 }, link: { border: "1px solid #cbd5e1", background: "#fff", borderRadius: 6, padding: "9px 12px", color: "#1f2937", textDecoration: "none", fontWeight: 800 }, grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14, marginBottom: 22 }, panel: { background: "#fff", border: "1px solid #d5dde6", borderRadius: 8, padding: 20, boxShadow: "0 1px 2px rgba(15,23,42,.06)" }, row: { padding: "10px 0", borderBottom: "1px solid #e5e7eb", color: "#4b5563" } };

export function DocumentsDemo({ view = "overview", audience = "school" }: { view?: string; audience?: string }) {
  const metrics = documentsDemoData.metrics;
  return <main style={styles.page}><header style={styles.header}><div><div style={styles.eyebrow}>SafeSchool Phase 10</div><h1 style={styles.title}>Documents, Certificates & Search</h1><p style={styles.subtitle}>Document metadata, object references, certificates, scoped search, retention, legal hold, controlled exports, and access decisions.</p></div><div style={styles.badge}>Demo data</div></header><nav style={styles.nav}><a style={styles.link} href="/documents">Documents</a><a style={styles.link} href="/documents/upload">Upload</a><a style={styles.link} href="/certificates">Certificates</a><a style={styles.link} href="/search">Search</a><a style={styles.link} href="/guardian/documents">Guardian</a><a style={styles.link} href="/student/documents">Student</a></nav><section style={styles.grid}>{metrics.map((metric) => <article key={metric.label} style={styles.panel}><strong style={{ fontSize: 32 }}>{metric.value}</strong><div>{metric.label}</div></article>)}</section><section style={styles.panel}><h2>{view} - {audience}</h2>{documentsDemoData.rows.map((row) => <div key={row} style={styles.row}>{row}</div>)}<p style={{ color: "#64748b" }}>Tenant-scoped, permission-checked, audited, and side-effect bounded.</p></section></main>;
}
