name: safeschool_mobile
description: SafeSchool role-based NFC mobile demo app.
publish_to: none
version: 12.0.0+1200
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
