using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using SafeSchool.Api.Features.AttendanceAccess;
using SafeSchool.Api.Features.AttendanceAccess.Anomalies;
using SafeSchool.Api.Features.AttendanceAccess.Attendance;
using SafeSchool.Api.Features.AttendanceAccess.Audit;
using SafeSchool.Api.Features.AttendanceAccess.Common;
using SafeSchool.Api.Features.AttendanceAccess.Common.Idempotency;
using SafeSchool.Api.Features.AttendanceAccess.Gates;
using SafeSchool.Api.Features.AttendanceAccess.Notifications;
using SafeSchool.Api.Features.AttendanceAccess.Reviews;
using SafeSchool.Api.Features.AttendanceAccess.Scans;
using SafeSchool.Api.Features.AttendanceAccess.Sync;
using SafeSchool.Api.Features.IdentityAccess;
using SafeSchool.Api.Features.IdentityAccess.AccessControl;
using SafeSchool.Api.Features.IdentityAccess.AccessControl.Authorization;
using SafeSchool.Api.Features.IdentityAccess.Audit;
using SafeSchool.Api.Features.IdentityAccess.Credentials;
using SafeSchool.Api.Features.IdentityAccess.Guardians;
using SafeSchool.Api.Features.IdentityAccess.StudentProfiles;
using SafeSchool.Api.Infrastructure.Errors;
using SafeSchool.Api.Infrastructure.FeatureFlags;
using SafeSchool.Api.Infrastructure.Persistence;
using SafeSchool.Api.Infrastructure.Tenancy;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer();
builder.Services.AddAuthorization();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddScoped<ITenantContext, TenantContext>();
builder.Services.AddScoped<IFeatureGateService, FeatureGateService>();
builder.Services.AddScoped<PermissionGuard>();
builder.Services.AddScoped<PermissionEvaluator>();
builder.Services.AddScoped<IAuditWriter, AuditWriter>();
builder.Services.AddScoped<IAccessDecisionWriter, AccessDecisionWriter>();
builder.Services.AddScoped<DuplicateStudentProfileDetector>();
builder.Services.AddScoped<StudentProfileAuditAdapter>();
builder.Services.AddScoped<StudentProfileService>();
builder.Services.AddScoped<RolePermissionService>();
builder.Services.AddScoped<GuardianAuditAdapter>();
builder.Services.AddScoped<GuardianService>();
builder.Services.AddScoped<GuardianLinkService>();
builder.Services.AddScoped<GuardianVisibilityService>();
builder.Services.AddScoped<CredentialAuditAdapter>();
builder.Services.AddScoped<CredentialLifecycleService>();
builder.Services.AddScoped<QrFallbackCredentialService>();
builder.Services.AddScoped<CredentialStatusSnapshotService>();
builder.Services.AddScoped<IClock, SystemClock>();
builder.Services.AddScoped<AttendanceAccessFeatureGate>();
builder.Services.AddScoped<AttendanceAccessPermissionGuard>();
builder.Services.AddScoped<IIdentityCredentialEvidenceProvider, DefaultIdentityCredentialEvidenceProvider>();
builder.Services.AddScoped<IGuardianLinkEligibilityProvider, DefaultGuardianLinkEligibilityProvider>();
builder.Services.AddScoped<IExpectedStudentPopulationProvider, DefaultExpectedStudentPopulationProvider>();
builder.Services.AddScoped<IdempotencyService>();
builder.Services.AddScoped<IAttendanceAccessAuditWriter, AttendanceAccessAuditWriter>();
builder.Services.AddScoped<GateService>();
builder.Services.AddScoped<ScanPointService>();
builder.Services.AddScoped<ScanValidationService>();
builder.Services.AddScoped<CampusAccessDecisionService>();
builder.Services.AddScoped<OfflineScanSyncService>();
builder.Services.AddScoped<ScanTraceService>();
builder.Services.AddScoped<GateScanAuditAdapter>();
builder.Services.AddScoped<AttendanceSessionService>();
builder.Services.AddScoped<AttendanceRuleEvaluator>();
builder.Services.AddScoped<AttendanceGenerationService>();
builder.Services.AddScoped<AttendanceCorrectionService>();
builder.Services.AddScoped<AttendanceSummaryService>();
builder.Services.AddScoped<AttendanceAuditAdapter>();
builder.Services.AddScoped<EntryExitNotificationEligibilityService>();
builder.Services.AddScoped<EntryExitNotificationService>();
builder.Services.AddScoped<GuardianEntryExitVisibilityService>();
builder.Services.AddScoped<EntryExitNotificationAuditAdapter>();
builder.Services.AddScoped<EntryExitNotificationWorkflowHooks>();
builder.Services.AddScoped<AnomalyDetectionRuleSet>();
builder.Services.AddScoped<AnomalyDetectionService>();
builder.Services.AddScoped<AnomalyReviewService>();
builder.Services.AddScoped<ManualReviewService>();
builder.Services.AddScoped<AnomalyAuditAdapter>();
builder.Services.AddDbContext<SafeSchoolDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("SafeSchool")));

var app = builder.Build();
app.UseMiddleware<ApiErrorMiddleware>();
app.UseMiddleware<TenantResolutionMiddleware>();
app.UseAuthentication();
app.UseAuthorization();
app.MapIdentityAccessEndpoints();
app.MapAttendanceAccessEndpoints();
app.MapGet("/health", () => Results.Ok(new { status = "ok" }));
app.Run();

public partial class Program;
