using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using SafeSchool.Api.Features.AttendanceAccess;
using SafeSchool.Api.Features.Administration;
using SafeSchool.Api.Features.Documents;
using SafeSchool.Api.Features.Communications;
using SafeSchool.Api.Features.Complaints;
using SafeSchool.Api.Features.AttendanceAccess.Anomalies;
using SafeSchool.Api.Features.AttendanceAccess.Attendance;
using SafeSchool.Api.Features.AttendanceAccess.Audit;
using SafeSchool.Api.Features.AttendanceAccess.Common;
using SafeSchool.Api.Features.AttendanceAccess.Common.Idempotency;
using SafeSchool.Api.Features.AttendanceAccess.Gates;
using SafeSchool.Api.Features.AttendanceAccess.Notifications;
using SafeSchool.Api.Features.AttendanceAccess.Reviews;
using SafeSchool.Api.Features.AttendanceAccess.Scans;
using SafeSchool.Api.Features.AttendanceAccess.Sync;
using SafeSchool.Api.Features.IdentityAccess;
using SafeSchool.Api.Features.IdentityAccess.AccessControl;
using SafeSchool.Api.Features.IdentityAccess.AccessControl.Authorization;
using SafeSchool.Api.Features.IdentityAccess.Audit;
using SafeSchool.Api.Features.IdentityAccess.Credentials;
using SafeSchool.Api.Features.IdentityAccess.Guardians;
using SafeSchool.Api.Features.IdentityAccess.StudentProfiles;
using SafeSchool.Api.Features.Learning;
using SafeSchool.Api.Features.Medical;
using SafeSchool.Api.Features.Mobile;
using SafeSchool.Api.Features.Requests;
using SafeSchool.Api.Features.Transport;
using SafeSchool.Api.Features.Transport.Anomalies;
using SafeSchool.Api.Features.Transport.Assignments;
using SafeSchool.Api.Features.Transport.Audit;
using SafeSchool.Api.Features.Transport.Common;
using SafeSchool.Api.Features.Transport.Common.Boundaries;
using SafeSchool.Api.Features.Transport.Common.Idempotency;
using SafeSchool.Api.Features.Transport.Common.Identity;
using SafeSchool.Api.Features.Transport.Eta;
using SafeSchool.Api.Features.Transport.Notifications;
using SafeSchool.Api.Features.Transport.Routes;
using SafeSchool.Api.Features.Transport.Rules;
using SafeSchool.Api.Features.Transport.Scans;
using SafeSchool.Api.Features.Transport.Sync;
using SafeSchool.Api.Features.Transport.Tracking;
using SafeSchool.Api.Features.Transport.Trips;
using SafeSchool.Api.Features.Transport.Reviews;
using SafeSchool.Api.Features.Wallet;
using SafeSchool.Api.Features.Wallet.Anomalies;
using SafeSchool.Api.Features.Wallet.Audit;
using SafeSchool.Api.Features.Wallet.Canteen;
using SafeSchool.Api.Features.Wallet.Common;
using SafeSchool.Api.Features.Wallet.Common.Boundaries;
using SafeSchool.Api.Features.Wallet.Common.Idempotency;
using SafeSchool.Api.Features.Wallet.Common.Identity;
using SafeSchool.Api.Features.Wallet.Common.Money;
using SafeSchool.Api.Features.Wallet.Corrections;
using SafeSchool.Api.Features.Wallet.History;
using SafeSchool.Api.Features.Wallet.Ledger;
using SafeSchool.Api.Features.Wallet.Limits;
using SafeSchool.Api.Features.Wallet.Payments;
using SafeSchool.Api.Features.Wallet.Pos;
using SafeSchool.Api.Features.Wallet.Reconciliation;
using SafeSchool.Api.Features.Wallet.Reviews;
using SafeSchool.Api.Features.Wallet.Rules;
using SafeSchool.Api.Features.Wallet.Sync;
using SafeSchool.Api.Features.Wallet.TopUps;
using SafeSchool.Api.Features.Wallet.Wallets;
using SafeSchool.Api.Infrastructure.Configuration;
using SafeSchool.Api.Infrastructure.Errors;
using SafeSchool.Api.Infrastructure.FeatureFlags;
using SafeSchool.Api.Infrastructure.Persistence;
using SafeSchool.Api.Infrastructure.Tenancy;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
{
    options.Authority = builder.Configuration["Jwt:Authority"];
    options.Audience = builder.Configuration["Jwt:Audience"];
    options.RequireHttpsMetadata = !builder.Environment.IsDevelopment();
});
builder.Services.AddAuthorization(options =>
{
    if (!builder.Configuration.GetValue<bool>("Demo:AllowAnonymousApi"))
    {
        options.FallbackPolicy = new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build();
    }
});
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddScoped<ITenantContext, TenantContext>();
builder.Services.AddScoped<IFeatureGateService, FeatureGateService>();
builder.Services.AddScoped<PermissionGuard>();
builder.Services.AddScoped<PermissionEvaluator>();
builder.Services.AddScoped<IAuditWriter, AuditWriter>();
builder.Services.AddScoped<IAccessDecisionWriter, AccessDecisionWriter>();
builder.Services.AddScoped<DuplicateStudentProfileDetector>();
builder.Services.AddScoped<StudentProfileAuditAdapter>();
builder.Services.AddScoped<StudentProfileService>();
builder.Services.AddScoped<RolePermissionService>();
builder.Services.AddScoped<GuardianAuditAdapter>();
builder.Services.AddScoped<GuardianService>();
builder.Services.AddScoped<GuardianLinkService>();
builder.Services.AddScoped<GuardianVisibilityService>();
builder.Services.AddScoped<CredentialAuditAdapter>();
builder.Services.AddScoped<CredentialLifecycleService>();
builder.Services.AddScoped<QrFallbackCredentialService>();
builder.Services.AddScoped<CredentialStatusSnapshotService>();
builder.Services.AddScoped<IClock, SystemClock>();
builder.Services.AddScoped<AttendanceAccessFeatureGate>();
builder.Services.AddScoped<AttendanceAccessPermissionGuard>();
builder.Services.AddScoped<IIdentityCredentialEvidenceProvider, DefaultIdentityCredentialEvidenceProvider>();
builder.Services.AddScoped<IGuardianLinkEligibilityProvider, DefaultGuardianLinkEligibilityProvider>();
builder.Services.AddScoped<IExpectedStudentPopulationProvider, DefaultExpectedStudentPopulationProvider>();
builder.Services.AddScoped<IdempotencyService>();
builder.Services.AddScoped<IAttendanceAccessAuditWriter, AttendanceAccessAuditWriter>();
builder.Services.AddScoped<GateService>();
builder.Services.AddScoped<ScanPointService>();
builder.Services.AddScoped<ScanValidationService>();
builder.Services.AddScoped<CampusAccessDecisionService>();
builder.Services.AddScoped<OfflineScanSyncService>();
builder.Services.AddScoped<ScanTraceService>();
builder.Services.AddScoped<GateScanAuditAdapter>();
builder.Services.AddScoped<AttendanceSessionService>();
builder.Services.AddScoped<AttendanceRuleEvaluator>();
builder.Services.AddScoped<AttendanceGenerationService>();
builder.Services.AddScoped<AttendanceCorrectionService>();
builder.Services.AddScoped<AttendanceSummaryService>();
builder.Services.AddScoped<AttendanceAuditAdapter>();
builder.Services.AddScoped<EntryExitNotificationEligibilityService>();
builder.Services.AddScoped<EntryExitNotificationService>();
builder.Services.AddScoped<GuardianEntryExitVisibilityService>();
builder.Services.AddScoped<EntryExitNotificationAuditAdapter>();
builder.Services.AddScoped<EntryExitNotificationWorkflowHooks>();
builder.Services.AddScoped<AnomalyDetectionRuleSet>();
builder.Services.AddScoped<AnomalyDetectionService>();
builder.Services.AddScoped<AnomalyReviewService>();
builder.Services.AddScoped<ManualReviewService>();
builder.Services.AddScoped<AnomalyAuditAdapter>();
builder.Services.AddScoped<ITransportClock, SystemTransportClock>();
builder.Services.AddScoped<TransportFeatureGate>();
builder.Services.AddScoped<TransportPermissionGuard>();
builder.Services.AddScoped<IStudentProfileEvidenceProvider, DefaultStudentProfileEvidenceProvider>();
builder.Services.AddScoped<ITransportCredentialEvidenceProvider, DefaultTransportCredentialEvidenceProvider>();
builder.Services.AddScoped<ITransportGuardianLinkProvider, DefaultTransportGuardianLinkProvider>();
builder.Services.AddScoped<IAttendanceAccessBoundary, AttendanceAccessBoundary>();
builder.Services.AddScoped<TransportIdempotencyService>();
builder.Services.AddScoped<ITransportAuditWriter, TransportAuditWriter>();
builder.Services.AddScoped<TransportRouteService>();
builder.Services.AddScoped<TransportStopService>();
builder.Services.AddScoped<RouteStopSequenceService>();
builder.Services.AddScoped<RouteTraceService>();
builder.Services.AddScoped<RouteStopAuditAdapter>();
builder.Services.AddScoped<TransportVehicleService>();
builder.Services.AddScoped<StudentTransportAssignmentService>();
builder.Services.AddScoped<AssignmentEligibilityService>();
builder.Services.AddScoped<GuardianTransportPlanVisibilityService>();
builder.Services.AddScoped<AssignmentTraceService>();
builder.Services.AddScoped<BusAssignmentAuditAdapter>();
builder.Services.AddScoped<TransportTripLifecycleService>();
builder.Services.AddScoped<TransportTripScanContextService>();
builder.Services.AddScoped<BoardingDropScanValidationService>();
builder.Services.AddScoped<TransportStatusDecisionService>();
builder.Services.AddScoped<ScanAnomalyCreationService>();
builder.Services.AddScoped<OfflineTransportScanSyncService>();
builder.Services.AddScoped<BoardingDropScanTraceService>();
builder.Services.AddScoped<BoardingDropScanAuditAdapter>();
builder.Services.AddScoped<LocationUpdateValidationService>();
builder.Services.AddScoped<TransportLocationUpdateService>();
builder.Services.AddScoped<GuardianTripProgressService>();
builder.Services.AddScoped<LocationRetentionService>();
builder.Services.AddScoped<TripTraceService>();
builder.Services.AddScoped<LiveTrackingAuditAdapter>();
builder.Services.AddScoped<EtaCalculationService>();
builder.Services.AddScoped<GuardianEtaVisibilityService>();
builder.Services.AddScoped<MaterialEtaChangeService>();
builder.Services.AddScoped<EtaTraceService>();
builder.Services.AddScoped<EtaAuditAdapter>();
builder.Services.AddScoped<TransportNotificationEligibilityService>();
builder.Services.AddScoped<TransportNotificationService>();
builder.Services.AddScoped<GuardianTransportNotificationVisibilityService>();
builder.Services.AddScoped<TransportNotificationWithdrawalService>();
builder.Services.AddScoped<TransportNotificationTraceService>();
builder.Services.AddScoped<TransportNotificationAuditAdapter>();
builder.Services.AddScoped<TransportNotificationWorkflowHooks>();
builder.Services.AddScoped<TransportAnomalyDetectionService>();
builder.Services.AddScoped<TransportAnomalyReviewService>();
builder.Services.AddScoped<ManualTransportReviewService>();
builder.Services.AddScoped<TransportRuleSettingService>();
builder.Services.AddScoped<TransportReviewSummaryService>();
builder.Services.AddScoped<IWalletClock, SystemWalletClock>();
builder.Services.AddScoped<WalletFeatureGate>();
builder.Services.AddScoped<WalletPermissionGuard>();
builder.Services.AddScoped<IWalletStudentProfileEvidenceProvider, DefaultWalletStudentProfileEvidenceProvider>();
builder.Services.AddScoped<IWalletGuardianLinkProvider, DefaultWalletGuardianLinkProvider>();
builder.Services.AddScoped<IWalletCredentialEvidenceProvider, DefaultWalletCredentialEvidenceProvider>();
builder.Services.AddScoped<IWalletAttendanceAccessBoundary, WalletAttendanceAccessBoundary>();
builder.Services.AddScoped<IWalletTransportOutcomeBoundary, WalletTransportOutcomeBoundary>();
builder.Services.AddScoped<WalletMoneyValidator>();
builder.Services.AddScoped<WalletIdempotencyService>();
builder.Services.AddScoped<IWalletAuditWriter, WalletAuditWriter>();
builder.Services.AddScoped<WalletRuleSettingValidator>();
builder.Services.AddScoped<WalletRuleSettingService>();
builder.Services.AddScoped<StudentWalletService>();
builder.Services.AddScoped<GuardianWalletVisibilityService>();
builder.Services.AddScoped<WalletLedgerPostingService>();
builder.Services.AddScoped<WalletLedgerQueryService>();
builder.Services.AddScoped<WalletBalanceProjectionService>();
builder.Services.AddScoped<WalletTraceService>();
builder.Services.AddScoped<WalletLedgerAuditAdapter>();
builder.Services.AddScoped<GuardianTopUpService>();
builder.Services.AddScoped<CashierTopUpService>();
builder.Services.AddScoped<TopUpQueryService>();
builder.Services.AddScoped<TopUpTraceService>();
builder.Services.AddScoped<IPaymentProviderAdapter>(serviceProvider =>
{
    var configuration = serviceProvider.GetRequiredService<IConfiguration>();
    var environment = serviceProvider.GetRequiredService<IHostEnvironment>();
    var adapter = configuration["Wallet:PaymentProvider:Adapter"];
    if (RuntimeConfigurationValidator.IsDemoPaymentProvider(adapter))
    {
        if (!environment.IsDevelopment() && !configuration.GetValue<bool>("Demo:AllowDemoPaymentProvider"))
        {
            throw new InvalidOperationException("DemoPay payment adapter is disabled outside Development.");
        }

        return new DemoPaymentProviderAdapter();
    }

    return new ConfiguredPaymentProviderAdapter(configuration);
});
builder.Services.AddScoped<PaymentConfirmationService>();
builder.Services.AddScoped<ChargebackRecoveryService>();
builder.Services.AddScoped<CanteenCatalogService>();
builder.Services.AddScoped<POSTerminalService>();
builder.Services.AddScoped<WalletPosCredentialValidationService>();
builder.Services.AddScoped<IWalletSpendingRuleEvaluationPort, WalletSpendingRuleEvaluationPort>();
builder.Services.AddScoped<OnlinePurchaseAuthorizationService>();
builder.Services.AddScoped<OfflinePosReserveService>();
builder.Services.AddScoped<OfflinePosSyncService>();
builder.Services.AddScoped<CanteenPurchaseQueryService>();
builder.Services.AddScoped<CanteenPurchaseTraceService>();
builder.Services.AddScoped<SpendingLimitManagementService>();
builder.Services.AddScoped<SpendingLimitEvaluationService>();
builder.Services.AddScoped<SpendingLimitTraceService>();
builder.Services.AddScoped<TransactionHistoryQueryService>();
builder.Services.AddScoped<WalletCorrectionService>();
builder.Services.AddScoped<ManualWalletReviewService>();
builder.Services.AddScoped<WalletAnomalyDetectionService>();
builder.Services.AddScoped<WalletAnomalyReviewService>();
builder.Services.AddScoped<TransactionTraceService>();
builder.Services.AddScoped<WalletReconciliationService>();
builder.Services.AddScoped<SettlementReferenceService>();
builder.Services.AddScoped<WalletReviewSummaryService>();
builder.Services.AddScoped<WalletRetentionService>();
builder.Services.AddScoped<WalletReconciliationTraceService>();
builder.Services.AddLearningFeature();
builder.Services.AddRequestsFeature();
builder.Services.AddMedicalFeature();
builder.Services.AddAdministrationFeature();
builder.Services.AddDocumentsFeature();
builder.Services.AddCommunicationsFeature();
builder.Services.AddComplaintsFeature();
builder.Services.AddMobileFeature();
builder.Services.AddDbContext<SafeSchoolDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("SafeSchool")));

var app = builder.Build();
RuntimeConfigurationValidator.Validate(app.Configuration, app.Environment);
app.UseMiddleware<ApiErrorMiddleware>();
app.UseMiddleware<TenantResolutionMiddleware>();
app.UseAuthentication();
app.UseAuthorization();
app.MapIdentityAccessEndpoints();
app.MapAttendanceAccessEndpoints();
app.MapTransportEndpoints();
app.MapWalletEndpoints();
app.MapLearningEndpoints();
app.MapRequestsEndpoints();
app.MapMedicalEndpoints();
app.MapAdministrationEndpoints();
app.MapDocumentsEndpoints();
app.MapCommunicationsEndpoints();
app.MapComplaintsEndpoints();
app.MapMobileEndpoints();
app.MapGet("/health", () => Results.Ok(new { status = "ok" })).AllowAnonymous();
app.Run();

public partial class Program;
